version: "3"

services:
  app:
    container_name: "api"
    environment:
      HOGE: HOGE
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports: 
      - 3001:3001
    restart: always
    volumes: 
      - .:/app/
    command: sh -c "npm run start:dev"